const random = {
  int: function (a, b) { return Math.floor(Math.random() * (b - a + 1)) + a },
  float: function (a, b) { return (Math.random() * (b - a + 1)) + a - 1 },
}

function json(data,method) {
  let back
  try { 
    data=JSON.parse(data)
    if (data.length == 2) { 
    back = `\n The Random Number Is : **${random[method](data[0], data[1])}**` } 
    else {    
      back = ' Check Your Input!'  }
  }
  catch (error) {
    back = ' Check Your Input!'
  }
  return back
}

let sleep = ms => { return new Promise(resolve => setTimeout(resolve, ms)) };

const Discord = require("discord.js.old")
const client = new Discord.Client()

client.on("message", msg => {
  if (!msg.author.bot) {
    if (/\$_facts\s+[0-9]+/.test(msg.content)) {
      let ret = facts.sort((a, b) => { return 0.5 - Math.random() })
      let num = msg.content.replace(/\$_facts\s+/, "")
      num = parseInt(num)
      if (num < 1) { num = 1 }
      if (num > facts.length/10) { num = Math.floor( facts.length/10 )*10 }

      ret.sort((a, b) => { return Math.random() })
      async function f() {

        for (let i = 0; i < num; i++) {
          await sleep(1000)
          const embed = new Discord.RichEmbed()
            .setColor([Math.random() * 155 + 100, Math.random() * 155 + 100, Math.random() * 155 + 100])
            .setTitle(`Fact ${i + 1}:`)
            .setDescription(`${ret[i]}`)
            .setFooter('Did You Like The Fact');
          //`Fact ${i+1} : \n-> ${ret[i]}`
          let react = msg.channel.send({ content: msg.author, embed: embed })
          react.then(m => m.react('👍'))
          react.then(m => m.react('👎'))
        }
      }
      f()
    }
    if (msg.content == '$dev') {
      msg.channel.send(
        ` Developer: Aditya Nambiar  \n Hosted By: YT .`)
    }
    if (msg.content.substr(0, "$info".length) == "$info") {
      msg.channel.send(`We Have **${facts.length - 1}+** Facts.`)
    }
    if (msg.content.substr(0, "$f_help".length) == "$f_help") {
      let embed = new Discord.RichEmbed()
        .setColor([Math.random() * 155 + 100, Math.random() * 155 + 100, Math.random() * 155 + 100])
        .setTitle(`Help`)
        .setDescription(`\n > Type $_facts *n* to get *n* random facts (*n* must be between *1* and *10*). \n\n > Type $random_int *a* , *b* For Obtaining A random **INTEGER** between *a* and *b*.\n\n > Type $random_decimal *a* , *b* For Obtaining A random **DECIMAL NO.** between *a* and *b*.\n\n > Type $info For More Information.`)

      msg.channel.send({ content: msg.author, embed: embed })
    }

    if (msg.content.substr(0, "$random_int".length) == "$random_int") {
      let data = msg.content.replace(/\$random_int\s+/, "")
      data = '[' + data + ']'
      msg.reply(json(data,'int'))
    }

    if (msg.content.substr(0, "$random_decimal".length) == "$random_decimal") {
      let data = msg.content.replace(/\$random_decimal\s+/, "")
      data = '[' + data + ']'
      msg.reply(json(data,'float'))
    }
    if (msg.content.substr(0, "$coin_toss".length) == "$coin_toss") {
      if (Math.random()>0.5) {msg.reply("\n > Coin Showed **HEADS**")} 
      else {msg.reply("\n > Coin Showed **TAILS**")}
    }
    if (msg.content.substr(0, "$dice_roll".length) == "$dice_roll") {
      msg.reply(`\n > The Number Is \`${random.int(1, 6)}\``)
    }

  }
})

client.login('MTA3OTQ2Mzk0ODQ1NTI2MDIzMA.GTh_iQ.jP6JCLOTTRCJ8y58gv2fI8G5XpjQf0oTQQ50Is')

let facts = [
  "The scientific term for brain freeze is \"sphenopalatine ganglioneuralgia.\"",
  "Canadians say \"sorry\" so much that a law was passed in 2009 declaring that an apology can't be used as evidence of admission to guilt.",
  "Back when dinosaurs existed, there used to be volcanoes that were erupting on the moon.",
  "The only letter that doesn't appear on the periodic table is J.",
  "One habit of intelligent humans is being easily annoyed by people around them but saying nothing in order to avoid a meaningless argument.",
  "If a Polar Bear and a Grizzly Bear mate, their offspring is called a \"Pizzy Bear.\"",
  "In 2006, a Coca-Cola employee offered to sell Coca-Cola secrets to Pepsi. Pepsi responded by notifying Coca-Cola.",
  "The ten highest mountain summits in the United States are all located in Alaska.",
  "Nintendo trademarked the phrase \"It's on like Donkey Kong\" in 2010.",
  "The famous line in Titanic from Leonardo DiCaprio, \"I'm king of the world!\" was improvised.",
  "A single strand of Spaghetti is called a \"Spaghetto.\"",
  "Hershey's Kisses are named after the kissing sound the deposited chocolate makes as it falls from the machine on the conveyor belt.",
  "Princess Peach didn't move until 1988 because it was too complicated for the designers to make her a movable character.",
  "To leave a party without telling anyone is called in English a \"French Exit.\" In French, it's called a \"partir à l'anglaise,\" to leave like the English.",
  "If you cut down a cactus in Arizona, you'll be penalized for up to 25 years in jail. It is similar to cutting down a protected tree species.",
  "The Buddha commonly depicted in statues and pictures is a different person entirely. The real Buddha was actually incredibly skinny because of self-deprivation.",
  "In Colorado, USA, there is still an active volcano. It last erupted about the same time as the pyramids were being built in Egypt.",
  "The first movie ever to put out a motion-picture soundtrack was Snow White and the Seven Dwarves.",
  "Fruit stickers are edible, though the same as any fruit; washing prior to eating is recommended. The glue used for them is regulated by the FDA.",
  "The scientific name for Giant Anteater is Myrmecophaga Tridactyla. This means \"ant eating with three fingers.\"",
  "Astronaut is a compound word derived from the two Ancient Greek words \"Astro,\" meaning \"star,\" and \"naut\" meaning \"sailor.\" So astronaut literally means \"star sailor.\"",
  "The flashes of colored light you see when you rub your eyes are called \"phosphenes.\"",
  "At birth, a baby panda is smaller than a mouse.",
  "Iceland does not have a railway system.",
  "The largest known prime number has 17,425,170 digits. The new prime number is 2 multiplied by itself 57,885,161 times, minus 1.",
  "Forrest Fenn, an art dealer and author hid a treasure chest in the Rocky Mountains worth over 1 million dollars. It was found approximately a decade later, in 2020.",
  "The lead singer of The Offspring started attending school to achieve a doctorate in molecular biology while still in the band. He graduated in May 2017.",
  "The tongue is the only muscle in one's body that is attached from one end.",
  "There is a company in Japan that has schools that teach you how to be funny. The first one opened in 1982. About 1,000 students take the course each year.",
  "The Lego Group is the world's most powerful brand. There are more Lego Minifigures than there are people on Earth.",
  "The Bagheera kiplingi spider was discovered in the 1800s and is the only species of spider that has been classified as vegetarian.",
  "There is a boss in Metal Gear Solid 3 that can be defeated by not playing the game for a week; or by changing the date.",
  "The Roman - Persian wars are the longest in history, lasting over 680 years. They began in 54 BC and ended in 628 AD.",
  "Elvis was originally blonde. He started coloring his hair black for an edgier look. Sometimes, he would touch it up himself using shoe polish.",
  "If you translate \"Jesus\" from Hebrew to English, the correct translation is \"Joshua.\" The name \"Jesus\" comes from translating the name from Hebrew to Greek to Latin to English.",
  "Ed Sheeran bought a ticket to LA with no contacts. He was spotted by Jamie Foxx, who offered him the use of his recording studio and a bed in his Hollywood home for six weeks.",
  "The first service animals were established in Germany during World War I. References to service animals date as far back as the mid-16th Century.",
  "An 11-year-old girl proposed the name for Pluto after the Roman god of the Underworld.",
  "The voice actor of SpongeBob and the voice actor of Karen, Plankton's computer wife, have been married since 1995.",
  "An Italian banker, Gilberto Baschiera, is considered a modern-day Robin Hood. Over the course of 7 years, he secretly diverted 1 million euros to poorer clients from the wealthy ones so they could qualify for loans. He made no profit and avoided jail in 2018 due to a plea bargain.",
  "Octopuses and squids have beaks. The beak is made of keratin - the same material that a bird's beak and our fingernails are made of.",
  "An estimated 50% of all gold ever mined on Earth came from a single plateau in South Africa: Witwatersrand.",
  "75% of the world's diet is produced from just 12 plants and five different animal species.",
  "The original Star Wars premiered on just 32 screens across the U.S. in 1977. This was to produce buzz as the release widened to more theaters.",
  "The British government coined the slogan, \"Keep Calm and Carry on,\" during World War 2 in order to motivate citizens to stay strong.",
  "Tirana, the capital of Albania, has a lot of things in common with other European capitals - except one. It's one of two capitals without a Mcdonald's. The second is Vatican City.",
  "Sour Patch Kids are from the same manufacturer as Swedish Fish. The red Sour Patch Kids are the same candy as Swedish Fish, but with sour sugar.",
  "The largest Japanese population outside of Japan stands at 1.6 million people who live in Brazil.",
  "IKEA is an acronym that stands for Ingvar Kamprad Elmtaryd Agunnaryd, which is the founder's name, the farm where he grew up, and his hometown.",
  "In 2009, Stephen Hawking held a reception for time travelers but didn't publicize it until after. This way, only those who could time travel would be able to attend. Nobody else attended.",
  "Violin bows are commonly made from horse hair.",
  "There are less than 30 ships in the Royal Canadian Navy which are less than most third-world countries.",
  "Larry the Cable Guy's real name is Daniel Lawrence Whitney. His notable Southern accent is fake - he was born and raised in the midwest, not the South.",
  "The youngest Pope in history was Pope Benedict IX, who was 11 years old at the time of the election. He is also the only person to have been the Pope more than once.",
  "Costa Coffee employs Gennaro Pelliccia as a coffee taster, who has had his tongue insured for £10 million since 2009.",
  "Johnny Cash took only three voice lessons before his teacher advised him to stop taking lessons and to never deviate from his natural voice.",
  "There is an island called \"Just Enough Room,\" where there's just enough room for a tree and a house.",
  "People who post their fitness routine on Facebook are more likely to have psychological problems.",
  "Medieval chastity belts are a myth. A great majority of examples now existing were made in the 18th and 19th centuries as jokes.",
  "Nowadays, millionaires with just $1 million aren't considered wealthy anymore by most Americans. Now, the typical American sees at least $2.4 million as wealthy.",
  "Hanna-Barbera pitched The Flintstones to networks for 8 weeks before it was finally picked up. It became the first-ever animated show to air during primetime.",
  "There is a company that sells mirrors that make people look 10 pounds thinner. Overall, the mirrors have contributed to 54% of total sales for retailers that use them.",
  "There's no period in \"Dr. Pepper.\" It was removed because the old logo font made it look like \"Di: Pepper.\"",
  "Standing around burns calories. On average, a 150-pound person burns 114 calories per hour while standing and doing nothing.",
  "Although GPS is free for the world to use, it costs $2 million per day to operate. The money comes from American tax revenue.",
  "In World War II, Germany tried to collapse the British economy by dropping millions of counterfeit bills over London.",
  "The human eye is so sensitive that if the Earth were flat and it was a dark night, a candle's flame could be seen from 30 miles away.",
  "When Space Invaders was created, Tomohiro Nishikado left in the lag caused by more invaders on the screen in order to create greater difficulty in the games.",
  "The color red doesn't really make bulls angry; they are color-blind.",
  "65% of autistic kids are left-handed, and only 10% of people, in general, are left-handed.",
  "In 2007, Scotland spent £125,000 devising a new national slogan. The winning entry was: \"Welcome to Scotland.\"",
  "Until 2016, the \"Happy Birthday\" song was not for public use. Meaning that prior to 2016, the song was copyrighted, and you had to pay a license to use it.",
  "There is a punctuation mark used to signify irony or sarcasm that looks like a backward question mark ⸮",
  "Lettuce is a member of the sunflower family.",
  "Researchers have found that flossing your teeth can help your memory. Flossing prevents gum disease, which prevents stiff blood vessels, which cause memory issues.",
  "A cluster of bananas is called a \"hand.\" Along that theme, a single banana is called a \"finger.\"",
  "The Hobbit has been published in two editions. In the first edition, Gollum willingly bet on his ring in the riddle game.",
  "For nearly 60 years, Texas didn't have an official state flag between 1879 & 1933. During that time, the Lone Star flag was active, but the unofficial flag.",
  "A wildlife technician, Richard Thomas, took the famous tongue twister, \"how much wood would a woodchuck chuck if a woodchuck could chuck wood\" and calculated a rough estimate of what the answer would actually be. It came out to be around 700 pounds.",
  "Red Solo cups are a common souvenir to bring back from the United States. The novelty comes from the cups being used in many party scenes in movies.",
  "Swedish meatballs originated from a recipe King Charles XII brought back from Turkey in the early 1800s.",
  "Those cute furry bits inside a cat's ear are called \"ear furnishings.\" They ensure that dirt doesn't go inside and also helps them to hear well.",
  "Scientists discovered sharks living in an active underwater volcano. Divers cannot investigate because they would get burns from the acidity and heat.",
  "There are times when Pluto is closer to the Sun than Neptune - one of these timelines was from 1979 to 1999.",
  "There is a town in Nebraska called Monowi with a population of one. The only resident is a woman who is the Mayor, Bartender, and Librarian.",
  "The Ethiopian calendar is 7.5 years behind the Gregorian calendar due to the fact that it has 13 months.",
  "In 1994, the company that had a patent on GIFs tried to charge a fee for using GIFS. The PNG was invented as an alternative, and the company backed down.",
  "China is spending $3 billion dollars to build panda-shaped solar farms in order to get more young people interested in renewable energy.",
  "Mercury and Venus are the only two planets in our solar system that do not have any moons.",
  "The average American child is given $3.70 per tooth that falls out.",
  "To properly write adjectives in order, you would list them by amount, value, size, temperature, age, shape, color, origin, and material.",
  "The world's first motel is in San Luis Obispo, which was built in 1925. When opened, it cost $1.25 for a two-room bungalow with a kitchen and a private adjoining garage.",
  "Scotland was one of the few countries able to hold off being conquered by the Romans in the first century A.D.",
  "I Will Always Love You was originally written and recorded in 1973 by Dolly Parton. It was written as a farewell to her mentor of seven years.",
  "\"Opposites attract\" is a common myth. People are actually attracted to people who look like family members or those with a similar personality type.",
  "Llamas can be used as guards against coyote attacks on sheep herds. Studies have proven that just one guard llama is an effective protector and can even kill the attacking coyotes.",
  "The unique smell of rain actually comes from plant oils, bacteria, and ozone.",
  "Vanilla flavoring is sometimes made with the urine of beavers.",
  "If you heat up a magnet, it will lose its magnetism.",
  "The most expensive virtual object is \"Club NEVERDIE\" in the Entropia Universe, which is worth $635,000. It was originally bought at $10,000.",
  "Cruise ships have morgues that can store up to 10 bodies at once. The average amount of people that die on cruise ships per year is 200.",
  "Birds are the closest living relatives of crocodilians, as well as the descendants of extinct dinosaurs with feathers. This makes them the only surviving dinosaurs.",
  "Small as they may be, ladybugs have a unique smell that humans are incredibly sensitive to.",
  "During WWII, a U.S. naval destroyer won a battle against a Japanese submarine by throwing potatoes at them. The Japanese thought they were grenades.",
  "The Marshal Mathers foundation for at-risk and disadvantaged youth was founded by Eminem.",
  "A man with severe OCD and a phobia of germs attempted to commit suicide with a gun to his head. Instead of killing him, the bullet eliminated his mental illness without any other damage.",
  "Since 1955, 50% of the population of Niger is consistently under 16 years old. The total current population is 21,600,000.",
  "The author of Mary Had a Little Lamb, Sarah Josepha Hale, is most responsible for the creation of Thanksgiving being a national holiday.",
  "The oldest unopened bottle of wine was found in a Roman tomb that is over 1,650 years old.",
  "Chicken Run is the highest-grossing stop-motion animated film, even beating The Nightmare Before Christmas.",
  "Nobody knows how the Academy Awards came to be referred to as the Oscars. The earliest mention was in 1932 and was made official in 1939.",
  "More tornadoes occur in the United Kingdom per square mile than in any other country in the world.",
  "Owners of personalized license plates in Uganda are facing a tax increase of over 300%, which will raise the tax from $1,498 to $5,992.",
  "Popularized by Shakespeare's play, many people think Julius Caesar's last words were, \"And you, Brutus?\" In reality, he said, \"You too, my child?\"",
  "Times Square was originally called Longacre Square until it was renamed in 1904 after The New York Times moved its headquarters to the newly built Times Building.",
  "Daniel Craig was an anonymous Storm Trooper in Star Wars: The Force Awakens. Originally, he denied his cameo and claimed he wouldn't bother being an extra in a movie.",
  "Queen Elizabeth II had a personal net worth of 425 million dollars. That includes the $65 million Sandringham House and $140 million Balmoral Castle.",
  "Although there is currently no drug proven to make someone tell the truth, some countries like Russia, Canada, and India use truth serums.",
  "Only primates, humans, and opossums have opposable thumbs. Out of these, the opossum is the only one with no thumbnail.",
  "One of the World Trade Centers was built to be 1,776 feet tall on purpose to reference the year the Declaration of Independence was signed.",
  "The word \"kimono\" literally means a \"thing to wear.\" Ki is \"wear,\" and mono is \"thing.\"",
  "There is a statue of Tesla in Silicon Valley that radiates free Wi-Fi. It was done as an homage to his vision for wireless communication.",
  "It snows metal on planet Venus! There are two types that have been found, galena and bismuthinite.",
  "Tic Tacs got their name from the sound they make when they are tossed around in their container.",
  "Only official members of federally accepted Native American tribes may legally possess or collect eagle feathers. If a normal citizen has one, it is illegal.",
  "By the time they have been retired for 2 years, 78% of former NFL players have gone bankrupt or are under financial stress because of joblessness or divorce.",
  "500 seeds of 5 different types of seeds were taken into orbit around the moon and later planted around the U.S. as well as a few countries. They were called Moon Trees.",
  "In order to protest the high tariffs enforced by a U.K. censorship board, a filmmaker sent in a 10-hour \"movie\" of white paint drying. They had to watch the entire film.",
  "The popular LMFAO group that created the viral hit, Party Rock Anthem, is made up of an uncle-nephew duo.",
  "50% of apartments in Los Angeles don't come with a fridge. This is legal, as fridges are considered an \"amenity,\" and therefore, landlords are not required to provide one.",
  "Norway has a 25-year statute of limitation on murder. This means if the murder happened more than 25 years ago, they cannot be charged.",
  "Several of the facts on Snapple caps have been found to be outdated, incorrect, or exaggerated.",
  "Both of the drummers from Queen and Duran Duran had the same name - Roger Taylor.",
  "There is a company in the U.K. that offers \"being hungover\" as a valid reason for calling off work. They are allotted four hungover days per year.",
  "The majority of blind people in the U.S. and the U.K. cannot read braille. Statistically, less than 1% of blind in the U.K. and under 10% in the U.S.",
  "It's not just humans who are right or left-handed. Most female cats prefer using their right paw, and males are more likely to be left-pawed.",
  "Over 290 people have died climbing Mount Everest since 1922. Most deaths occur because of avalanches, and not all bodies have been recovered.",
  "There are only two countries in the world that have the color purple in their flags: Nicaragua and Dominica.",
  "A bolt of lightning can reach 53,540 degrees Fahrenheit. That's 5 times hotter than the surface of the sun, which is 10,340 degrees Fahrenheit.",
  "There is a village in Russia called Tsovkra where every resident can tightrope walk. It is a tradition that dates back over 100 years, but no one knows how it started.",
  "When Shakira was in second grade, she was rejected by the school choir because her vibrato was too strong. The music teacher told her that she sounded like a goat.",
  "Four of the top seven highest-grossing films of all time were released in 2015. Avengers: Age of Ultron, Furious 7, Jurassic World, and Star Wars: The Force Awakens.",
  "Four Nile crocodiles have been found in Florida. They are the second-largest crocodile and are more dangerous than the native crocodiles and alligators in Florida.",
  "Julius Caesar's only son, Caesarion, was the last Pharaoh of Egypt. Even though Cleopatra swears he is Caesar's son, Caesar never officially acknowledged him.",
  "The quietest room in the world in Minnesota is measured in negative decibels - so quiet that you can hear your own heartbeat and your bones moving.",
  "\"Tsundoku\" is a Japanese word for the habit of buying too many books, letting them pile up in your house, and never reading them.",
  "The Guinness World Record for the longest time spent searching for the Loch Ness Monster is held by Steve Feltham, who camped at Loch Ness for 25 years.",
  "Brain fibers lose 10% of their total length every decade. They can shrink even more so under acute stress.",
  "Chewing gum boosts mental proficiency and is considered a better test aid than caffeine - but nobody knows why.",
  "Per capita, the happiest countries in the world also rank highest in terms of consumers of antidepressants.",
  "Even though Irish is the official language of Ireland, Polish is more widely spoken.",
  "There's a bar in Yukon that serves a \"Sourtoe cocktail.\" It consists of a shot of whisky with a human toe floating in the glass. An estimated 60,000 people have had it.",
  "The Stockholm archipelago has more islands than the Pacific Ocean, at around 30,000.",
  "Pope Francis has been given many extravagant gifts over the years, and one of them was a Harley-Davidson motorcycle. However, rather than keeping it for his own pleasure and adventures, he sold it off and used the money to benefit homeless people.",
  "In Japan, Domino's started testing pizza delivery via reindeer in 2016.",
  "The motto on the United Kingdom's Royal Coat of Arms is in French. The motto is \"Dieu et mon droit,\" which means \"God and my right.\"",
  "The average household income of the top 1% in the United States is $1,260,508 per year.",
  "Disney sold the streaming right for the original Star Wars films in 2016 to Turner until 2024. Disney has since decided to start a streaming service and has tried asking for the rights back, but Turner refuses every time.",
  "Gaming-related accidents increased by 26.5% during the first 5 months of Pokemon Go being released. This included 2 deaths and $25.5 million in damages.",
  "Helen Keller was related to Robert E. Lee. Her paternal grandmother was second-cousins with him.",
  "During the 1908 Olympics in London, the Russians showed up 12 days late due to the fact that they were using the Julian calendar instead of the Gregorian calendar.",
  "Non-violent attempts to escape Mexican prisons are not punished because \"it's human nature to want freedom.\"",
  "The line \"Born and raised in South Detroit\" in Journey's \"Don't Stop Believin\" actually refers to Canada, not Michigan.",
  "On one slow news day on April 18, 1930, a BBC radio announcer blatantly said, \"there is no news.\"",
  "If you cut a starfish, it won't bleed - it doesn't have blood! Rather, they circulate nutrients by using seawater in their vascular system.",
  "12% of the world's total languages are found in Papua New Guinea, which has over 820 indigenous languages. There are more languages on this island than in any other country.",
  "The hottest temperature ever recorded in Washington state was at Ice Harbor Dam at 118 °F (47.8 °C) on August 5, 1961.",
  "In efforts to undercut the Dreamcast's sales of the upcoming SEGA release, Sony announced the PlayStation 2 and exaggerated its performance capabilities.",
  "Nepal has the most mathematical flag in the world. It even has an article in its constitution that details the steps of drawing the flag.",
  "Mount Rushmore cost less than one million dollars to construct. It took 14 years to build - from 1927 to 1941 and took 400 workers.",
  "Samsung means \"three stars\" in Korean. This was chosen by the founder because he wanted the company to be powerful and everlasting, like stars in the sky.",
  "On average, 46.1% of Americans have less than $10,000 in assets when they die.",
  "While shedding, geckos will eat their skin in order to prevent predators from finding and eating them more easily.",
  "Bees actually have knees. The expression comes from the fact that they store large build-ups of pollen in hairy baskets on their knees.",
  "Between North and South Korea lies 155 miles of no man's land, where hundreds of rare animal species thrive.",
  "While watching a Merry-Go-Round from a bench in Griffith Park, Los Angeles, Walt Disney was struck with inspiration for the creation of Disneyland.",
  "There is a Scottish tartan designed for Mars exploration. It was officially registered in 2016 to be worn during Mars science, exploration, and outreach activities.",
  "Santa Claus was issued a pilot's license by the U.S. government in 1927. They also gave him airway maps and promised to keep the runway lights on.",
  "When you exercise, the burned fat metabolizes to become carbon dioxide, water, and energy. Meaning that you exhale the fat that you lose.",
  "The word \"velociraptor\" comes from the Latin words \"velox\" which means swift, and \"raptor,\" which means robber. Literally - speedy robber!",
  "The largest stadium in the world is the Rungrado 1st of May Stadium in North Korea. It can hold up to 114,000 spectators. It covers 51 acres and is 197 feet tall.",
  "Polar bears often hunt walruses by simply charging at a group of them and eating the ones that were crushed or wounded in the mass panic to escape. Direct attacks are rare.",
  "The group of spikes at the end of stegosaurid tails is called the \"thagomizer.\" They had no distinct name until the term was coined in 1982 by a cartoonist.",
  "There is a correlation between pulling an all-nighter and snapping out of depression. This is because the brain gets more active the longer it goes without sleep.",
  "Adult cats only meow at humans, not other cats. Kittens meow to their mother, but once they get a little older, cats no longer meow to other cats.",
  "When shuffling a deck of cards, the number of possible arrangements is approximately 8×1067. That's more than the number of stars in the observable universe.",
  "There is a United Arab Emirates territory inside Oman's territory that itself is inside the United Arab Emirates country. It is called Madha village.",
  "Disappointment Island is an uninhabited island in New Zealand. Over 65,000 pairs of white-capped albatross live there. In 1868, a steel tanker crashed on the island, which killed 68 people, leaving the 15 survivors waiting 18 months to be rescued. In 1907, another ship ended up crashing there, and 12 men drowned.",
  "During the entire run of Gilligan's Island, it was never revealed if \"Gilligan\" was his first or last name.",
  "When Jorge Garcia first got the part on LOST as Hurley, he lost a total of 30 pounds in weight before filming started.",
  "Videogames have been found to be more effective at battling depression than therapy.",
  "Bi-weekly has two different definitions: Twice a week or once every two weeks.",
  "Mona Lisa was stolen from the Louvre in 1911, which drew more visitors to see the empty space than the actual painting.",
  "There is an insurance policy issued against alien abduction. Around 50,000 policies have been sold, mainly to residents of the U.S. and England.",
  "Volvo invented the three-point seatbelt, then gave the invention away for free. They decided it was too important of an invention to keep to themselves.",
  "The bull is the most common motif on Indus seals",
  "Lebanon is the only Arab country that does not have any desert. The place has traditionally been an important commercial hub for the Middle East.",
  "Full Form Of AMUL , India's largest milk federation is Anand Milk Union Limited",
  "On April 3, 1984, Rakesh Sharma flew on board Soyuz T-11 with two Soviet cosmonauts, commander Yury Malyshev and flight engineer Gennady Strekalov, to the space station Salyut 7 , Becoming the first Indian to go to space. He stayed there for 7 days 21 hours and 40 minutes",
  "Cartilage and the cornea are the only types of tissue in the human body that do not contain blood vessels",
  "Bangkok is the world's most visited city.",
  "Typing keyboards used to be arranged alphabetically.",
  "We are born with only 2 natural fears: the fear of falling and the fear of loud sounds.",
  "Baked beans are not actually baked.",
  "Antarctica is the only continent without any reptiles or snakes.",
  "Video games help surgeons perform better.",
  "Tomato ketchup was used as medicine for 16 years.",
  "The brain is the fattest organ.",
  "Australia has the most number of venomous snakes worldwide.",
  "Dead people get goosebumps.",
  "You can't move or touch William Shakespeare's bones.",
  "\"Digging a hole to China\" is possible if you start in Argentina.",
  "A snail can sleep for three years.",
  "A musician named Jim Sullivan mysteriously disappeared 6 years after recording an album called \"U.F.O.\"",
  "The name for the Pringles shape is a hyperbolic paraboloid.",
  "There is McDonald's in all continents except Antarctica.",
  "At any point in time, 0.7% of the world's population is drunk.",
  "Sonic the Hedgehog isn't his full name.",
  "A crocodile cannot stick its tongue out.",
  "Like fingerprints, everyone's tongue print is different.",
  "Toilet paper in France is generally pink.",
  "Artificial banana flavoring is based on an extinct banana.",
  "Four out of the ten largest statues in the world are of Buddhas.",
  "Squeaky floors were the best home security in 17th century Japan.",
  "Half of all bank robberies in the U.S. are done on a Friday.",
  "Tinder made its first match in Antarctica in 2014.",
  "Men's dress shirt collars used to be detachable.",
  "The first novel in the world ended mid-sentence.",
  "In 2014, a missing woman on a vacation in Iceland was found in a search party for herself.",
  "Sneezing while traveling at 60 mph makes you close your eyes for 50 feet.",
  "People don't sneeze in their sleep.",
  "If you make $1 every second, it will take you 2,921 years to be richer than Bill Gates.",
  "February used to be the last month of the year.",
  "Shoe shops used X-Ray machines to measure shoe sizes.",
  "The Big Ben in London is leaning so much that the incline is visible to the naked eye.",
  "Australia has the most beaches in the world.",
  "The national animal of Scotland is the Unicorn.",
  "The directors of the film Despicable Me wrote their own language for the Minions.",
  "Alaska had a cat mayor.",
  "There is an island in the Bahamas with only pigs as residents.",
  "Eating polar bear liver can kill a human being.",
  "Insects are attracted to light because of the moon.",
  "Lobster used to be considered the cockroach of the ocean.",
  "DreamWorks studios was created by a former Disney employee.",
  "Australia has a bright pink lake.",
  "Netflix spent $0 on marketing its DVD rental business, but over 6 million people still used it.",
  "Spiked and studded dog-collars were an Ancient Greek invention.",
  "A full jumbo jet tank has enough fuel to drive a car around the world four times.",
  "Artist Salvador Dali would get out of paying at restaurants by drawing on the checks.",
  "Jellyfish almost caused mass nuclear explosions in 2013.",
  "A seaman once set a ship on fire to get out of work early.",
  "Tea bags were an accidental invention.",
  "Your heart beats 100,000 times a day.",
  "J is the only letter that doesn't appear on the periodic table.",
  "A man once won a horse race after he died.",
  "At birth, baby pandas are smaller than mice.",
  "Jack Daniel was believed to die from kicking a safe.",
  "A coffee taster has his tongue insured for £10 million.",
  "Herring fish communicate by farting.",
  "A kimono literally translates to \"thing to wear.\"",
  "Scientists grew a human tooth from scratch using pee.",
  "Tic Tacs got their name from the sound they make.",
  "You could go to jail for collecting eagle feathers in the U.S.",
  "78% of NFL players undergo financial crisis by 2 years of retirement.",
  "Moon Trees are a thing.",
  "A filmmaker once created a 10-hour \"film\" of paint drying.",
  "During the first 5 months of Pokémon Go, gaming-related accidents increased by 26.5%.",
  "If you ate nothing but rabbit meat, you would die from protein poisoning.",
  "Hundreds of rare animals and plants thrive in the North Korea-South Korea border.",
  "The tongue is the only muscle in the body attached from one end.",
  "In a conversation, each speaker's \"turn\" is 2 seconds, with intervals between turns only 200 milliseconds.",
  "Sleep literally cleanses your brain.",
  "Sudan has the most pyramids out of any country.",
  "The Lego Group is the most powerful brand in the world.",
  "Mr. and Mrs. came from the words master and mistress.",
  "The only difference between kosher salt and table salt is the grain size.",
  "Humans specifically have eyes that face forward for the purpose of seeing in 3D.",
  "The founder of Pringles, Fredric Baur, requested to be buried in a Pringles can.",
  "The sound of a Star Wars lightsaber is the combined sound of a film projector and noise from an old TV.",
  "Humans can't taste food without saliva.",
  "There's a plankton that reverses your feeling of hot and cold.",
  "You can eat the stickers on fruit.",
  "Scientists don't know what causes the shower-curtain effect.",
  "The Chanel double C was the first designer logo of all time.",
  "Giraffes have less neck bones than a sloth.",
  "The word \"friends\" is said in every episode of Friends.",
  "Manatees can get cold stress.",
  "Not sporty? Try aggressive sitting.",
  "27,000 trees are cut per day for the world's toilet paper.",
  "May 22nd is the least common birth date.",
  "No one knows for sure how dinosaurs mate.",
  "Airport runway numbers actually indicate the direction on a compass.",
  "Hershey's Kisses were named that after the kissing sound the chocolate makes on the conveyor belt.",
  "Butterflies taste with their feet.",
  "Penguins can jump as high as 9 feet in the air.",
  "Polar bears aren't purely left-handed.",
  "A frog can throw up an entire organ.",
  "The legs of a bat are so thin, they can't walk.",
  "The katydid bug hears through holes in its hind legs.",
  "Slugs only have one nose.",
  "A shrimp's heart is in its head.",
  "Chickens are eaten for their whole life cycle.",
  "Sharks can \"blink\" and \"wink\".",
  "Toilets usually flush in E flat.",
  "A raisin dropped in fresh champagne will keep bouncing up and down from the bottom to the top of the glass.",
  "It takes 142.18 licks to reach the center of a Tootsie pop.",
  "Human birth control pills work on gorillas.",
  "When the first Star Wars movie came out, France was still executing people with the guillotine.",
  "Queen Elizabeth II owns the swans in England.",
  "During World War II, the Oscar awards were made of painted plaster.",
  "For every non-porn webpage, there are five porn pages.",
  "Napoléon Bonaparte's penis was stolen.",
  "M&M's stands for \"Mars & Murrie's.\"",
  "Millions of trees were estimated to be planted by squirrels that forgot their buried nuts.",
  "A pound of houseflies contains more protein than a pound of beef.",
  "Cats sleep for ⅔ of their lives.",
  "Alfred Hitchcock's Psycho was the first American film to show a toilet being flushed on screen.",
  "The Eiffel Tower leans away from the sun.",
  "A laughing epidemic made 14 schools close in East Africa.",
  "The youngest parents in the world were aged 8 and 9.",
  "During WWI, Kotex was first manufactured as bandages.",
  "Drinking coffee in Turkey was once punishable by death.",
  "India was the first country to mine diamonds.",
  "Crocodile poop was the first contraceptive.",
  "The youngest Pope elected was 11 years old.",
  "Only 2 countries don't sell Coca-Cola.",
  "The Paris Agreement on climate change was signed by the largest number of countries ever in one day.",
  "The world's quietest room is located at Microsoft's headquarters in Washington state.",
  "Only 3 countries don't use the metric system.",
  "President Bush was re-elected by less than 31% of all eligible voters in the United States.",
  "Wayne's World was filmed in two weeks.",
  "Dodge made the first engines used by Ford.",
  "In Ancient Egypt , priests plucked their bodies bald.",
  "The population of the United States increases by one person every 12 seconds.",
  "Toto was paid $125 per week while filming The Wizard of Oz.",
  "The electric chair was invented by a dentist.",
  "Frankenstein is a vegetarian.",
  "The Terminator script was sold for a dollar.",
  "Computer mouse speed is measured in \"Mickeys.\"",
  "Pigeon poop is property of the British royal family.",
  "Ancient Egyptians slept on pillows made of stone.",
  "The microwave oven was another accidental invention.",
  "In Elizabethan England, the spoon was so novel and prized that people carried their own folding spoons to banquets.",
  "Millie the White House dog earned more than four times as President Bush in 1991.",
  "Nebraskan drivers had the flashiest traffic situation back then.",
  "Over 70% of people would reveal their passwords for chocolate.",
  "A Boeing 747 airliner is made of over 6,000,000 separate parts.",
  "The word \"testify\" is based on… testes?",
  "\"Pants\" used to be a dirty word.",
  "Palindromes are the most difficult kind of phrase to form.",
  "The oceans contain 200,000 different kinds of viruses.",
  "The tallest tower of cupcakes ever made is over 35 feet.",
  "The biggest grill out of all time had 394 people grilling meat.",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "A single lightning bolt has enough energy to toast 100,000 slices of bread.",
  "A blue whale's heartbeat can be heard from two miles away.",
  "The Netherlands has a squirrel bridge.",
  "Subway footlongs don't measure a foot long.",
  "Marie Curie's belongings still have radioactive residue in present day.",
  "The Canary Islands are named after dogs, not birds.",
  "The Netherlands has the tallest population.",
  "Indonesia has the shortest population.",
  "Tom Hanks was not paid for Forrest Gump.",
  "Arnold Schwarzenegger once forgot to take off the Terminator look.",
  "The sound of the automatic doors opening on the U.S.S. Enterprise is made by a toilet.",
  "Will Smith wanted to adopt the German Shepherd in I Am Legend.",
  "Henry Cavill's muscles are the real deal.",
  "The Titanic film runs for as long as the ship sunk.",
  "Sylvester Stallone landed in the I.C.U. while filming Rocky.",
  "Brad Pitt and Edward Norton actually learned how to make soap in Fight Club.",
  "Brendan Fraser almost died filming The Mummy.",
  "Arnold Schwarzenegger practiced with guns every day for a month to prepare for The Terminator.",
  "Daniel Kaluuya was given the lead role on the spot after nailing his audition.",
  "Michael Fassbender had makeup artists put alcohol on his mustache for a role.",
  "The Kingsman underwater scene was not scripted.",
  "The creators of Stranger Things wanted to direct the It remake.",
  "There were 25 snakes found on The Maze Runner set.",
  "Crushed vitamins have been used for cocaine scenes in movies.",
  "Nestlé supplied 1,850 bars of real chocolate for Charlie and the Chocolate Factory.",
  "Hugh Jackman went 36 hours without water for Les Miserables.",
  "Jim Caviezel was struck by lightning while playing Jesus in The Passion Of The Christ.",
  "Victorians said \"prunes\" when taking pictures.",
  "The foil seals on medicine bottles were placed due to poisoning incidents.",
  "North Koreans are shorter than South Koreans.",
  "Indians read the most out of any nationality.",
  "A pig was once held in trial for the death of a child.",
  "You could buy a town from eBay.",
  "Doritos are flammable.",
  "Starbucks flopped in Australia.",
  "Glaciers make sounds.",
  "The first roller coaster was invented to stop sinful behavior.",
  "Your nails grow at the same time as continental plates drift.",
  "The longest location name on the planet is 85 letters long.",
  "The people who are currently alive are only 7% of the total number of people who have ever lived.",
  "Muhammad is the most popular name in the world.",
  "There are more than 24 time zones around the world.",
  "Sweden has the most islands of any country.",
  "The red-billed quelea is the most common bird on Earth.",
  "The hashtag symbol is called an octothorpe.",
  "The longest wedding veil was longer than 63 football fields.",
  "No real astronaut ever said, \"Houston, we have a problem,\"",
  "The lyrebird can make chainsaw sounds.",
  "9% of Americans have phobias.",
  "Elvis only won 3 Grammys.",
  "Cornell University offers a wine course.",
  "The Krusty Krab restaurant is a lobster trap.",
  "The Hulk was supposed to be grey.",
  "The Flintstones was the highest-earning network cartoon franchise for 30 years.",
  "Walt Disney hated Goofy.",
  "The place that cartoon characters store things, just to pull out of thin air, is known as \"Hammerspace\".",
  "Superman used to leap places instead of flying.",
  "The longest-running primetime animated series is the Simpsons, which began in 1987.",
  "Mickey Mouse and Minnie Mouse were married in real life.",
  "The Pokemon Hitmonlee and Hitmonchan are based on Bruce Lee and Jackie Chan.",
  "All the Professors in Pokemon have been named after trees.",
  "Snow White and the Seven Dwarfs was the first American film to have a soundtrack.",
  "The Little Mermaid was Disney's first princess movie in 30 years.",
  "Jackie Chan voiced the Beast in the Chinese dub of The Beauty And The Beast.",
  "The Lion King was the first original Disney movie.",
  "Bees bite.",
  "Kids ask about 300 questions a day.",
  "T-shirts were originally made for unmarried men who didn't know how to sew buttons on collared shirts.",
  "All Froot Loops have the same flavor.",
  "Before the 1800s, people slept in batches.",
  "Cows have \"best friends\" and will get stressed when separated.",
  "New Zealanders have more pets per household than any other country.",
  "The design for the seatbelts we use now was given away by Volvo.",
  "Kea parrots laugh together when they're in a good mood.",
  "Flyting was the original rap battle.",
  "The Russians showed up 12 days late to the 1908 Olympics.",
  "In Japan, letting a sumo wrestler make your baby cry is considered good luck.",
  "Black cats are good luck in Britain and Japan.",
  "Ben & Jerry learned how to make ice cream from a $5 course at Penn State.",
  "The the official plural form of a Prius is Prii.",
  "Dogs can understand up to 250 words and gestures.",
  "Goats have rectangular pupils.",
  "Wasting food is illegal for supermarkets in France.",
  "A baby can cost new parents 750 hours of sleep.",
  "A grumble is a group of pugs.",
  "Garfield used to own G-Mail.",
  "Crayola is literally \"oily chalk.\"",
  "Abraham Lincoln was a wrestling champion.",
  "Queen Elizabeth II has had over 30 corgis in her lifetime.",
  "Relative to their bodies, Chihuahuas have the biggest brain in the dog world.",
  "Elvis Presley's manager sold hate merch for profit.",
  "Avocados never ripen on the tree.",
  "At the Humane Society of Missouri, kid volunteers comfort anxious shelter dogs by reading to them.",
  "China owns all of the pandas in the world.",
  "Penguins used to be 6 feet tall.",
  "A scientific calculator is 6 times more powerful than the Apollo 11 computer.",
  "Humans shed 18 kg of skin in their lifetime.",
  "The \"Like\" button on Facebook was supposed to be the \"Awesome\" button.",
  "Human fingers are really sensitive.",
  "Humans are genetically related to bananas.",
  "Our sense of smell and taste decrease by 20%-50% during flights.",
  "There are more atoms in a glass of water than glasses of water you could fill with all the oceans of the Earth.",
  "Bubble wrap was originally designed to be used as wallpaper.",
  "Your body replaces all its particles every seven years.",
  "The world's longest musical piece lasts 639 years.",
  "Neptune was the first planet that was discovered before being seen through a telescope.",
  "You're more likely to become President than you are to win the lottery.",
  "There's only one letter that doesn't appear in any U.S. state name.",
  "Samsung tests phone durability with a butt robot.",
  "Armadillos have bulletproof shells.",
  "Kleenex tissues were supposed to be for gas masks.",
  "Blue whales eat 500,000 calories in 1 mouthful.",
  "The tiny pocket in jeans is for pocket watches.",
  "NASA can \"fax\" tools to astronauts",
  "Only ¼ of the Sahara Desert is sandy.",
  "2 parts of the human body never stop growing.",
  "No number contains the letter A before 1,000.",
  "Mercedes invented a joystick-controlled car.",
  "The CIA headquarters Starbucks doesn't put names on the cups.",
  "The Eiffel Tower grows during the summer.",
  "Bees can fly higher than Mount Everest.",
  "Humans have jumped further than horses in the Olympics.",
  "A waffle iron inspired one of the first iconic Nike shoes.",
  "Glitter was invented by a farmer.",
  "Abraham Lincoln used to be a bartender.",
  "Beethoven never studied multiplication or division.",
  "Aquariums were supposed to be for cows.",
  "An espresso maker has been sent to space.",
  "Apple Inc. was founded on April Fool's.",
  "Wild boars wash their food.",
  "Baseball umpires used to sit in rocking chairs.",
  "The first commercial airplane flight lasted 23 minutes.",
  "The French Scrabble World Champion doesn't speak French",
  "A U.K. woman has called 911 because of ice cream.",
  "The British Empire was the largest empire in the world.",
  "Turtles can talk to each other.",
  "170 year-old champagne was found under the Baltic Sea.",
  "Nikola Tesla did not like pearls.",
  "Brad Pitt injured his Achilles heel while playing Achilles.",
  "Martin Luther King Jr. had a C in public speaking.",
  "Bees can make different colors of honey.",
  "The Pope can't donate organs.",
  "A one-armed player scored the winning goal in the first World Cup.",
  "The stick is the world's first toy.",
  "The first baby stroller was pulled by animals.",
  "Ancient Egyptians used dead mice for toothaches.",
  "Africa spans across the Northern , Eastern , Western & Southern Hemispheres",
  'Mercury & Venus are the only 2 planets in our solar system that have no moons.',
 'If a star passes too close to a black hole, it can be torn apart.',
 'The hottest planet in our solar system is Venus.',
 'Our solar system is 4.57 billion years old.',
 'Enceladus, one of Saturn’s smaller moons, reflects 90% of the Sun’s light.',
 'The highest mountain discovered is the Olympus Mons, which is located on Mars.',
 'The Whirlpool Galaxy (M51) was the first celestial object identified as being spiral.',
 'A light-year is the distance covered by light in a single year.',
 'The Milky Way galaxy is 105,700 light-years wide.',
 'The Sun weighs about 330,000 times more than Earth.',
 'Footprints left on the Moon won’t disappear as there is no wind.',
 'Because of lower gravity, a person who weighs 220 lbs on Earth would weigh 84 lbs on Mars.',
 'There are 79 known moons orbiting Jupiter.',
 'The Martian day is 24 hours 39 minutes and 35 seconds long.',
 'NASA’s Crater Observation and Sensing Satellite (L…OSS) found evidence of water on the Earth’s Moon.',
 'The Sun makes a full rotation once every 25 – 35 days.',
 'Earth is the only planet not named after a God.',
 'Due to the Sun and Moon’s gravitational pull, we have tides.',
 'Pluto is smaller than the United States.',
 'According to mathematics, white holes are possible, although as of yet we have found none.',
 'There are more volcanoes on Venus than any other planet in our solar system.',
 'Uranus’ blue glow is due to the gases in its atmosphere.',
 'In our solar system that are 4 planets known as gas giants: Jupiter, Saturn, Uranus & Neptune.',
 'Uranus has 27 moons that have been discovered so far.',
 'Because of its unique tilt, a season on Uranus is equivalent to 21 Earth years.',
 'Neptune’s moon, Triton, orbits the planet backwards.',
 'Triton is gradually getting closer to the planet it orbits.',
 'There are more stars in space than there are grains of sand in the world.',
 'Neptune takes nearly 165 Earth years to make one orbit of the Sun.',
 'Pluto’s largest moon, Charon, is half the size of Pluto.',
 'The International Space Station is the largest manned object ever sent into space.',
 'A day on Pluto is lasts for 153.6 hours long.',
 'Saturn is the second largest planet in our solar system.',
 'Any free-moving liquid in outer space will form itself into a sphere.',
 'Mercury, Venus, Earth & Mars are known as the “Inner Planets”.',
 'We know more about Mars and our Moon than we do about our oceans.',
 'The Black Arrow is the only British satellite to be launched using a British rocket.',
 'Only 5% of the universe is visible from Earth.',
 'Light travels from the Sun to the Earth in less than 10 minutes.',
 'At any given moment, there are at least 2,000 thunderstorms happening on Earth.',
 'The Earth’s rotation is slowing slightly as time goes on.',
 'If you were driving at 75 miles per hour, it would take 258 days to drive around Saturn’s rings.',
 'Outer Space is only 62 miles away.',
 'The International Space Station circles Earth every 92 minutes.',
 'Stars twinkle because of the way light is disrupted as it passes through Earth’s atmosphere.',
 'We always see the same side of the Moon, no matter where we stand on Earth.',
 'There are three main types of galaxies: elliptical, spiral & irregular.',
 'There are approximately 100 thousand million stars in the Milky Way.',
 'Using the naked eye, you can see 3 – 7 different galaxies from Earth.',
 'In 2016, scientists detected a radio signal from a source 5 billion light-years away.',
 'The closest galaxy to us is the Andromeda Galaxy – it’s estimated at 2.5 million light-years away.',
 'The first Supernovae observed outside of our own galaxy was in 1885.',
 'The first-ever black hole photographed is 3 million times the size of Earth.',
 'The distance between the Sun & Earth is defined as an Astronomical Unit.',
 'The second man on the moon was Buzz Aldrin. “Moon” was Aldrin’s mother’s maiden name.',
 'Buzz Aldrin’s birth name was Edwin Eugene Aldrin Jr.',
 'On Venus, it snows metal and rains sulfuric acid.',
 'The Mariner 10 was the first spacecraft that visited Mercury in 1974.',
 'Space is completely silent.',
 'Coca-Cola was the first commercial soft drink that was ever consumed in space.',
 'Astronauts can grow approximately two inches (5 cm) in height when in space.',
 'The Kuiper Belt is a region of the Solar System beyond the orbit of Neptune.',
 'The first woman in space was a Russian called Valentina Tereshkova.',
 'If Saturn’s rings were 3 feet long, they would be 10,000 times thinner than a razor blade.',
 'The Hubble Space Telescope is one of the most productive scientific instruments ever built.',
 'The first artificial satellite in space was called “Sputnik”.',
 'Exoplanets are planets that orbit around other stars.',
 'The center of the Milky Way smells like rum & tastes like raspberries.',
 'Our moon is moving away from Earth at a rate of 1.6 inch (4 cm) per year!',
 'Pluto is named after the Roman god of the underworld, not the Disney Dog.',
 'Spacesuit helmets have a Velcro patch, to help astronauts itch.',
 'The ISS is visible to more than 90% of the Earth’s population.',
 'Saturn is the only planet that could float in water.',
 'Asteroids are the byproducts of formations in the solar system, more than 4 billion years ago.',
 'Astronauts can’t burp in space.',
 'Uranus was originally called “George’s Star”.',
 'A sunset on Mars is blue.',
 'The Earth weighs about 81 times more than the Moon.',
 'The first living mammal to go into space was a dog named “Laika” from Russia.',
 'The word “astronaut” means “star sailor” in its origins.',
 '“NASA” stands for National Aeronautics and Space Administration.',
 'Gennady Padalka has spent more time in space than anyone else.',
 'Mercury has no atmosphere, which means there is no wind or weather.',
 'In China, the Milky Way is known as the “Silver River”.',
 'Red Dwarf stars that are low in mass can burn continually for up to 10 trillion years!',
 'Scientists once believed that the same side of Mercury always faced the Sun.',
 'Jupiter’s Red Spot is shrinking.',
 'A large percentage of asteroids are pulled in by Jupiter’s gravity.',
 'A day on Mercury is equivalent to 58 Earth days.',
 'As space has no gravity, pens won’t work.',
 'On average it takes the light only 1.3 seconds to travel from the Moon to Earth.',
 'There are 88 recognized star constellations in our night sky.',
 'The center of a comet is called a “nucleus”.',
 'As early as 240BC the Chinese began to document the appearance of Halley’s Comet.',
 'In 2006, the International Astronomical Union reclassified Pluto as a dwarf planet.',
 'There are 5 Dwarf Planets recognized in our Solar System.',
 'Mars is the most likely planet in our solar system to be hospitable to life.',
 'Halley’s Comet will pass over Earth again on July 26, 2061.',
 'There is a planet half the radius of the Earth with a surface made up of diamonds.',
 'Buzz Lightyear from Toy Story has actually been to outer space!'
]
